### ISSUE TITLE
New Assistant + Firefox.

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/BrowserAssistant#10]
@Vitalik93 commented on [Wed Jun 10 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3364)

Считаю что нужно доразобраться с текущей работой (точнее не работой) нового Помощника в браузере Firefox. Сейчас кроме как через ручную установку путём скачивания файла .xml Помощник не поставить и происходит это скорее всего из за политики Mozilla в отношении установки расширений из левых мест. Может стоит подумать про добавление Помощника в магазин расширений Mozilla с ведущей туда ссылкой из настроек AdGuard? Думаю этот вариант наиболее оптимальный. Ссылки на проблемные темы: [1)](https://forum.adguard.com/index.php?threads/cant-install-new-adguard-browser-extension.38555/#post-198552), [2)](https://github.com/AdguardTeam/AdguardForWindows/issues/3332)

**Comment by ameshkov** [comment]
Mozilla не дает добавлять такие расширения в AMO. У них там не могут быть расширений, которые требуют для работы еще какой-то софт.

> Помощник не поставить и происходит это скорее всего из за политики Mozilla в отношении установки расширений из левых мест

Это может происходить только из-за багов в FF, а не из-за политики.

**Comment by Vitalik93** [comment]
> Mozilla не дает добавлять такие расширения в AMO. У них там не могут быть расширений, которые требуют для работы еще какой-то софт.

Почему не дают? У меня давно стоит расширение ExpressVPN, которое тоже без программы не работает.

**Comment by ameshkov** [comment]
Да? Может быть поменялось у них что-то с тех времен. Посмотрим, спасибо

**Comment by NUser2018** [comment]
> 
> 
> Mozilla не дает добавлять такие расширения в AMO. У них там не могут быть расширений, которые требуют для работы еще какой-то софт.
> 
> 

> Да? Может быть поменялось у них что-то с тех времен.

Как было не знаю. Но сейчас видимо позволяют, поскольку на страницах дополнений к антивирусным продуктам Лаборатрии Касперского ([2020](https://addons.mozilla.org/ru/firefox/addon/kaspersky-protection-2020/) версия и [2021](https://addons.mozilla.org/ru/firefox/addon/kaspersky-protection-2021/) версия) прямо указано что для работы дополнения требуется еще и внешнее приложение установить. 

> Посмотрим, спасибо

Да уж посмотрите, поскольку проблема установки дополнения нового Браузерного Помощника Adguard в Firefox никуда не делась. Подробно она обсуждалась [ЗДЕСЬ](https://github.com/AdguardTeam/AdguardForWindows/issues/3332#issuecomment-634794819) и далее.

**Comment by NUser2018** [comment]
> Сейчас кроме как через ручную установку путём скачивания файла .xml Помощник не поставить

@Vitalik93 Достаточно просто временно выключить в антивирусе проверку защищенных соединений ну или проще просто временно закрыть (выгрузить) антивирус.

Но вообще это конечно костыль и не дело и проблему нужно как-то решать. Не все догадаются что это нужно сделать.
Команда Adguard конечно не может повлиять ни на антивирусы ни на Firefox, но достаточно просто добавить дополнение нового Помощника в официальный каталог дополнений Firefox а в программе сделать просто кнопку-ссылку на страницу нужного дополнения также как это уже происходит в последних версиях (как минимум 2020 и 2021) антивирусных продуктов Лаборатории Касперского.

Вообщем я уже давал в своем предыдущем комментарии [ссылку](https://github.com/AdguardTeam/AdguardForWindows/issues/3332#issuecomment-634794819) на подробное обсуждение этой проблемы.

**Comment by Vitalik93** [comment]
> Как было не знаю. Но сейчас видимо позволяют, поскольку на страницах дополнений к антивирусным продуктам Лаборатрии Касперского ([2020](https://addons.mozilla.org/ru/firefox/addon/kaspersky-protection-2020/) версия и [2021](https://addons.mozilla.org/ru/firefox/addon/kaspersky-protection-2021/) версия) прямо указано что для работы дополнения требуется еще и внешнее приложение установить.

Да, точно, Каспера еще забыл. Его аддон тоже без антивируса не работает, но тоже идёт из магазина расширений.

> Но вообще это конечно костыль...

Вот именно что костыль.

**Comment by dartraiden** [comment]
>  происходит это скорее всего из за политики Mozilla в отношении установки расширений из левых мест

Точно не из-за этого, потому что единственное требование - чтобы расширение было подписано.

**Comment by NUser2018** [comment]
**У меня вроде как проблема с неустановкой нового Браузерного Помощника в Firefox больше не воспроизводится!** 

Win10 x64 (64 bit) (версия 2004), Kaspersky Total Security (KTS) 2021 MR1 (21.1.15.500) (с патчем a) и Firefox 79.0 (64 bit).

@Vitalik93 и другие пользователи, а как у Вас!?

В случае сохранения у вас проблемы пожалуйста укажите свою краткую конфигурацию как и я выше.
