### ISSUE TITLE
AdGuard Assistant Browser popup can not be disabled 

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/BrowserAssistant#111]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version of the extension
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

```markdown
- AdGuard Assistant version: 1.3.40
- AdGuard Desktop application: 7.16.0
```

### Environment

```markdown
- OS:26016
- Browser: Microsoft Edge Version 121
```

### Issue Details

Steps to reproduce:
1. Open Browser
2. Adguard Assistant popup appears on every website

### Expected Behavior

AdGuard assistant popup does not appear or can be easily disabled.
I just want to be able to use the toolbar icon to manage AdGuard Assistant, and don't want to be bothered by a consistent popup on very website by AdGuard assistant.

### Actual Behavior
AdGuard Assistant Popup appears on every website.
![Screenshot 2024-01-02 160329](https://github.com/AdguardTeam/BrowserAssistant/assets/35312698/b7149196-22d5-4323-8a2e-e9882db51af4)

### Additional Information

It is rather annoying when your adblocker / popup blocker has a constant popup which cannot be disabled without disabling the whole extension.

**Comment by zubrRB** [comment]
This icon is from the Legacy Assistant, which you need to disable in your settings.

<details><summary>Screenshot:</summary>

![legacy](https://github.com/AdguardTeam/BrowserAssistant/assets/50718960/9b727b92-93e8-4731-b117-e6ac14e2bb38)
</details><br/>

**Comment by Samuel12321** [comment]
Thanks, That fixed it, didn't realize the AdGuard assistant entry under extensions was for the legacy assistant.
