### ISSUE TITLE
Version 1.4.1 Permissions Change?

### ISSUE THREAD

**Issue by verymucho** [AdguardTeam/BrowserAssistant#114]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version of the extension
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

```markdown
- AdGuard Assistant version: 1.4.1
- AdGuard Desktop application: AdGuard for Windows 7.17.0 nightly 22
```

### Environment

```markdown
- OS: Windows 11, 23H2, build 22631.3296
- Browser: Firefox Developer Edition 125.0b4
```

### Issue Details

Steps to reproduce:
1. Install version 1.4.1 of the Browser Assistant
2. Visit any website.
3. Have to click on the AdGuard Browser Assistant icon/button on the toolbar before protection is enabled for that site.
4. Repeat on every other site.

### Expected Behavior

Protection is enabled automatically for all sites (save for restricted sites like the add-on store, etc).

### Actual Behavior

Have to click on the AdGuard Browser Assistant icon/button on the browser toolbar before protection is enabled for each site I visit.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Going back to version 1.3.40 of the add-on works as expected.

**Comment by alexx7311** [comment]
@verymucho Hello! The extension gets access to the page only after clicking on the icon, but no access request is made by the extension before the click. This is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1851083) and it may seem like the extension is asking for permission every time, although it is not.

To avoid injecting content script into all pages, we added the `scripting` permission as `tabs.executeScript` cannot be used for Manifest V3. Link: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript.

We hope that Firefox developers will fix this, but it should not affect the behavior of the assistant.

**Comment by AngelosNaoumis** [comment]
Happens also to be in Brave Beta
Brave is up to date
[Version 1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (64-bit)](https://brave.com/latest/)

**Comment by alexx7311** [comment]
@AngelosNaoumis Hello! Couldn't reproduce it on Brave Beta.
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/BrowserAssistant/assets/114913601/ff184afb-2b95-447d-9e89-cd49b54b0ba1)

</details>
