### ISSUE TITLE
Browser Assistant runs amok in Firefox

### ISSUE THREAD

**Issue by GagomeSmirnja** [AdguardTeam/BrowserAssistant#115]
This problem happened to me already several times.

I run Adguard Browser Assitant in Firefox. Normally it works fine.
When I get a notification that a new version of Firefox is available I restart all my browser sessions to update Firefox.
All sessions close, Firefox updates and all windows do re-open.
And then I hear that the CPU fans begin to increase their noise. I see that CPU utilization goes up to >80%, the fan gets louder and I open the Process Explorer. There I see thousands and thousands of Adguard Browser Assistant processes open and more are opened every second.
All I can then do is immediately open the Add-on Manager in Firefox and disable Adguard Browser Extension before my PC slows down significantly becasue of the thousands Adguard Browser Assistant processes.

What may cause this?

Attached is the window from Process Explorer which shows the Adguard Browser Assistant processes ending (the red color) after I successfully disabled it in Firefox.

Firefox version is 124.0.1
OS is Windows 10 64-bit
Adguard is 7.16.0 (4542)

![20240329_Adguard_Browser_Extension_runs-amok](https://github.com/AdguardTeam/AdguardAssistant/assets/165406008/0ae140de-3a06-41af-b1ce-4a5f0fc49ef8)

**Comment by GagomeSmirnja** [comment]
Hello, I have now recreated the problem and I tried to collect all the data you have mentioned.
But the export of logs from AdGuard took very long. I had already disabled Browser Assistant before the export of logs completed.
I will send all data to the e-mail you have mentioned.
The problem started at 20:26:18.

**Comment by zubrRB** [comment]
I have been observing something similar for a long time in Chrome. https://github.com/AdguardTeam/AdguardForWindows/issues/4874#issuecomment-1788811781

**Comment by adbuker** [comment]
Seems, that the issue related to the fixed https://github.com/AdguardTeam/AdguardForWindows/issues/4874. @GagomeSmirnja, you can obtain the build with the fix switching to the nighty channel or wait nor more than a couple a weeks until 7.17 released
