### ISSUE TITLE
Permission error on Firefox 124. And maybe perhaps Chrome/Edge too.

### ISSUE THREAD

**Issue by Nekroz88** [AdguardTeam/BrowserAssistant#117]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version of the extension
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

```markdown
- AdGuard Assistant version: 1.4.1
- AdGuard Desktop application: 7.16.0 (4542)
```

### Environment

```markdown
- OS: Windows 10 64bit 22H2
- Browser: Firefox 124, Edge 123
```

### Issue Details

Steps to reproduce:
1. Use the latest version of extension on Firefox extension store
2. Access any site

### Expected Behavior

Firefox should say This extension can "Always" read and change data, instead of saying "on click".
And in Edge/Chrome extension settings, it should be saying This extension can read and change data "On all sites" like Adguard adblocker.

### Actual Behavior

Firefox says This extension can read and change data "on click".
Edge/Chrome says This extension can read and change data: without providing any site.

_The extension still seems to successfully block the ads despite there are permission errors though. But I think it would still be better to fix the permission for the extension._

### Screenshots

<details><summary>Screenshot 1:</summary>
![Screenshot (1)](https://github.com/AdguardTeam/BrowserAssistant/assets/101539308/2b0d4dae-c0d7-45bb-8073-47e65577229d)
![Screenshot 2024-04-16 095237](https://github.com/AdguardTeam/BrowserAssistant/assets/101539308/5200b85f-f915-4d60-8b06-91b1e2bbdd2a)
![Screenshot 2024-04-16 095221](https://github.com/AdguardTeam/BrowserAssistant/assets/101539308/3b93f424-3283-4feb-aea6-d30439ab8bff)
</details>

**Comment by alexx7311** [comment]
Dup. of https://github.com/AdguardTeam/BrowserAssistant/issues/114
