### ISSUE TITLE
Add blocked ads/trackers or fired scriptlets counter

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/BrowserAssistant#118]
Add a blocked trackers/ads counter visualiser in the extension logo or somewhere on the page. 

![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/73603712/e03bf6c5-9b72-4213-b644-456945f4b2b0)

**Comment by alexx7311** [comment]
@SpotlightForBugs We already have an [open issue for adding stats](https://github.com/AdguardTeam/BrowserAssistant/issues/35), we'll think more about whether to implement it. Thanks!
