### ISSUE TITLE
Incompatibility with Waterfox

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/BrowserAssistant#2]
### Environment

AdGuard 7.4n9, Assistant v0.0.22, Waterfox Stable

### Steps to reproduce

1. Install Assistant in Waterfox using Firefox addon store
2. The extension will be unable to detect AdGuard. See screenshot for error message

### Screenshot

![1](https://user-images.githubusercontent.com/33634917/77129944-9192ab80-6a5e-11ea-8479-f0d64c38f971.jpg)

### User ID
2144766

**Comment by freezewind** [comment]
More detail:
Waterfox current 2020.03 (Base on firefox 68)
Win10 1903
Installed Browser Assistant extension from https://adguard.com/en/adguard-assistant/overview.html
