### ISSUE TITLE
Feature request: Disable Assistant menu from the browser context menu

### ISSUE THREAD

**Issue by pdkpv** [AdguardTeam/BrowserAssistant#20]
Add an option in the extension settings Disable Assistant menu from the browser context menu.

Version **1.1.1**

![2020-11-17_12-54-42](https://user-images.githubusercontent.com/43634070/99376875-93a35780-28d6-11eb-8102-ca613bcb09d7.jpg)

**Comment by Chinaski1** [comment]
Hello there!

Yep, that a good idea! We will definitely add this feature in the next update  ;)

**Comment by rakleed** [comment]
@Chinaski1 is there any news on when this feature will be implemented? And then since November 19, 2020, 4 updates have already been released, but this function is still not supported.

**Comment by Chinaski1** [comment]
The addition of this feature is scheduled for version 1.2
