### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/BrowserAssistant#21]
Please add a dark theme. And make the default sync the extension theme with the system theme. More details: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by rakleed** [comment]
Added in version 1.2.2. Thanks!

**Comment by zubrRB** [comment]
В расширении ZenMate (Chrome) тёмную тему можно легко переключать вне зависимости от системной.

![Zen](https://user-images.githubusercontent.com/50718960/230927717-1b7c6681-a092-42b9-8ca8-b978162496bb.gif)
