### ISSUE TITLE
Upload Assistant to Edge Store and AMO

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/BrowserAssistant#22]
So here's what needs to be done:

1. We should upload the extensions (first to a draft, that's enough to generate the ID)
2. Make sure that the apps are aware of it and the add-on ID is included in the next beta or nightly
3. Publish the add-ons (don't change the links inside the apps just yet)
4. Once everything is up and running, change the links inside the apps so that they lead to the store pages
5. Once the apps are released - change the links on the website

This task should be converted to an "Epic" internally.

**Comment by TPS** [comment]
https://microsoftedge.microsoft.com/addons/detail/adguard-adblocker/pdffkfellgipmhklpdmokmckkkfcopbh?

**Comment by ameshkov** [comment]
@TPS this one is AG main extension, not Assistant.

**Comment by TPS** [comment]
I didn't realize there were actually _2_ extensions.  Does the Assistant interface with Adguard Windows, or how is it different?

I recognize Performix from the now-defunct Amazon Appstore listings, so no worries re: that.

**Comment by ameshkov** [comment]
@TPS 

> Does the Assistant interface with Adguard Windows, or how is it different?

Yes, Assistant does not actually do anything by itself. The only purpose of it is to provide an easy way to manage AdGuard for Win/Mac protection right from the browser.

**Comment by TPS** [comment]
Why isn't that folded into the _other_ AG extension?  I seem to remember an option for Integrated mode or some such?

**Comment by ameshkov** [comment]
It doesn't play well with the "Single-purpose policy" of CWS

**Comment by TPS** [comment]
Do the Edge store & AMO have the same policy?   Or would _that_ be too much work?

**Comment by ameshkov** [comment]
Yeah, definitely too much

**Comment by michaelb-ae** [comment]
any news on this ?, if you want some help i have a dev account and two extension on it.

**Comment by ameshkov** [comment]
Uploading is easy, but we should first update both Mac and Win apps so that they were aware of this Edge store extension.

**Comment by michaelb-ae** [comment]
When do you think this update will show up ? (7.5.4 for this support or this will wait 7.6 ?), i ask because i don't see 7.6 in beta for now it's for estimate an approxumative date.

**Comment by ameshkov** [comment]
It's 7.6 for sure.

**Comment by ameshkov** [comment]
AMO - done.
Edge on Mac - done
Edge on Win - will be included in v7.6.
