### ISSUE TITLE
Unable to view original certificate for IP site

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/BrowserAssistant#27]
For sites that use IP addresses instead of domain names, AdGuard Assistant cannot display the site's original certificate.

AdGuard Assistant says: HTTPS filtering was not performed for this website

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/110199696-9da49280-7e94-11eb-82eb-62af28fdb0f6.png)

</details>

but in fact, AdGuard still performs MitM on IP sites.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/110199735-d17fb800-7e94-11eb-9f33-e8aa206d2bdc.png)

</details>

**Comment by ameshkov** [comment]
Oh, very nice bug, thank you!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1422](https://github.com/AdguardTeam/CoreLibs/issues/1422) via [**ZenHub**](https://www.zenhub.com/)
