### ISSUE TITLE
Where is the future of WoT if legacy AG Assistant will be abandoned?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/BrowserAssistant#3]
Will WoT be integrated with new AG Assistant Browser Extension?

**Comment by ameshkov** [comment]
Hi! No, we won't integrate it with WoT. Anway, we keep WOT extension disabled by default since a long time ago due to the controversy of what they were doing with the customers' data.

**Comment by lancelot-moon** [comment]
It's better if it's optional like what it is in legacy AG Assistant.

**Comment by ameshkov** [comment]
Well, the problem is that we would like to get rid of it eventually
