### ISSUE TITLE
Manifest V3

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/BrowserAssistant#38]
Hello,
I want to ask, 
Since this extension is a compagnon for the main app, does it's work to switch to manifest V3 are in preparation / done ?
I ask (I have searched the manifest in the file but I don't have found it).

I know it's not very urgent I just ask to know if you planning it and if you have an idea (since it's a compagnon it can be done most faster.

**Comment by vozersky** [comment]
@BirdInFire Hi! Well, you can say it's in preparation, yeah, we are going to switch all the extensions to Manifest v3 at some point, starting with Extra.
