### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/BrowserAssistant#4]
https://chrome.google.com/webstore/detail/adguard-browser-assistant/hhaeiccdiaojoofohjiennalnphobkaf

1. The extension's name is untranslated on chrome web store.
I only see the phrase, "AdGuard Browser Assistant", on Crowdin.
Is it untranslated because it's a beta's name?
https://crowdin.com/translate/adguard-applications/18033/en-zhtw#3915009
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/lQM2Lvn.png)
</details><br/>

2. The short description and overview are untranslated on chrome web store.
Please upload the overview to Crowdin.
AG Browser Assistant v0.0.48 indeed provides Chinese Traditional interface, but the supported languages list doesn't contain Chinese Traditional on chrome web store. 
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7lLYLSV.png)
</details><br/>

3. The short description is untranslated at the bottom of the page on chrome web store.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/U4jOEAm.png)
</details><br/>

4. In extensions' tab of chrome, the name and short description are untranslated.
In the secure page of extensions' tab, the word, "extensions", is untranslated in UI.
Modify `extensions` to `chrome://extensions`.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/95Fiddc.png)
</details><br/>

5. In the secure page of new tab, the word, "newtab", is untranslated in UI.
Modify `newtab` to `chrome://newtab`.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/88a5B94.png)
</details><br/>

**Comment by lancelot-moon** [comment]
Well, for the 4th and 5th points, it shows `chrome://extensions/` and `chrome://newtab/` in AG Browser Extension.

You decide if they should be modified to `chrome://extensions/` and `chrome://newtab/`.

**Comment by maximtop** [comment]
`chrome://extensions` and `chrome://newtab` are URLs of service pages and we won't change them

**Comment by lancelot-moon** [comment]
But it's only `extensions` or `newtab` in the UI of AdGuard Browser Assistant when being in the secure page.
Will you change to use `chrome://extensions` or `chrome://newtab` in AdGuard Browser Assistant?

**Comment by maximtop** [comment]
this part would remain unchanged
