### ISSUE TITLE
Combine BrowserAssistant and AdGuardAsisstant

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/BrowserAssistant#42]
I use AdGuard across ~10 desktops. Some of these desktops have the AdGuard app, and some don't. On the desktops that use the AdGuard Apps, I use the new Browser Assistant as it syncronises with the app, and on the desktops that don't use the AdGuard app, I use the AdGuard assistant.

This can be a hassle when using browser sync, as I have to have extension sync turned off for each browser as it will generally sync in an extension I don't need on that browser.

Could this Browser Assistant be combined with the AdGuard assistant?

**Comment by vozersky** [comment]
@jslawler hi! didn't quite get it. "and on the desktops that don't use the AdGuard app, I use the AdGuard assistant"  - Do you mean AdGuard Adblocker extension?

**Comment by jslawler** [comment]
AdGuard Assistant (This gets synchronised with Browsers extension sync)
<img width="812" alt="Screen Shot 2021-11-11 at 06 08 31" src="https://user-images.githubusercontent.com/6005161/141186005-72d2b903-fe3f-40ac-8b54-a15dd755694c.png">

AdGuard AdBlocker Browser Extension (This ALSO gets synchronised with Browser extension sync)
<img width="1904" alt="Screen Shot 2021-11-11 at 06 08 40" src="https://user-images.githubusercontent.com/6005161/141185989-bb9e3b51-4710-4bef-897d-0eb2e41dc8a3.png">

I guess the issue with naming comes from the extensions various names. On the Chrome web store, it's called "AdGuard AdBlocker". In AdGuard for Mac, the same extension is called "AdGuard Assistant" under the Extensions tab. Then there's the "Assistant" tab, which refers to yet another version of the extension as a companion this time.
It also doesn't tell the user that ticking the "AdGuard Assistant Beta" option under Extensions is also a legacy extension, then automatically ticking the "Legacy Assistant" item under Assistant.
<img width="812" alt="Screen Shot 2021-11-11 at 06 09 42" src="https://user-images.githubusercontent.com/6005161/141186068-eeccc538-7dd5-4825-88d5-be0a555d9783.png">

I understand that some of these functions have different outputs, however could they not all be compiled into the same extension to negate the confusion?

**Comment by ameshkov** [comment]
Tbh, in the future, we're going to get rid of the Legacy Assistant completely and this should solve the confusion:)
