### ISSUE TITLE
Browser Assistant icon is still gray after protection re-enabled in AdGuard itself

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/BrowserAssistant#45]
Hello team! :wave:,
&nbsp;

Here is a small problem regarding the interaction between `AdGuard Browser Assistant` and `AdGuard`. 🙂
&nbsp;

## Steps to reproduce
&nbsp;

### [1/2] _Disable_ protection in AdGuard itself (via main UI or systray icon) or via AG Browser Assistant.
&nbsp;

![Screenshot 2021-11-04 023511](https://user-images.githubusercontent.com/4764956/140243006-490cf50e-51e2-4bc1-b228-b53d9397a1a2.png)
:heavy_check_mark: _Correct result produced in AdGuard._
&nbsp;

![Screenshot 2021-11-04 023615](https://user-images.githubusercontent.com/4764956/140243009-a7e58668-864d-488e-b876-df7945ec0ff3.png)
:heavy_check_mark: _Correct result produced in AdGuard Browser Assistant._
&nbsp;
&nbsp;

### [2/2] _Re-enable_ protection in AdGuard itself (via main UI or systray icon).
&nbsp;

![Screenshot 2021-11-04 023710](https://user-images.githubusercontent.com/4764956/140243521-69bbb30b-6ae2-4992-bef9-36cf73c1cbc9.png)
:heavy_check_mark: _Correct result produced in AdGuard._
&nbsp;

![Screenshot 2021-11-04 023816](https://user-images.githubusercontent.com/4764956/140243544-afa42c56-7e05-4f28-9c1e-437a1f819c58.png)
:heavy_multiplication_x: _**Incorrect** result produced in AdGuard Browser Assistant._
_(The shield color remains gray instead of switching to green, in the extension icon.)_
&nbsp;
&nbsp;

## :memo: Notes
&nbsp;

- No problem, however, if the protection is re-enabled via AdGuard Browser Assistant.
- Although somewhat similar to [this issue](https://github.com/AdguardTeam/BrowserAssistant/issues/41), it's different.
  - _(With notably an expected _opposite_ result concerning the color of the shield.)_
&nbsp;
&nbsp;

## :bulb: Interesting fact
&nbsp;

Both **Firefox** and **Edge** produce the expected result in one case: if the current tab is a built-in tab.
&nbsp;
:arrow_right_hook: _i.e. for **Firefox**: new tab page a.k.a. `about:newtab`, `about:blank`, `about:support`, …_
:arrow_right_hook: _i.e. for **Edge**: new tab page a.k.a. `edge://newtab`, `edge://version`, …_
&nbsp;
&nbsp;

## :computer: Environment
&nbsp;

- **AdGuard Browser Assistant version:**
  - 1.1.16 (used on **Firefox** 94.0)
  - _Reproducible also in:_ 1.1.11 (used on **Edge** 95.0.1020.40)
- **AdGuard version:** 7.7.1
- **OS information:** Windows 10 (21H1)
&nbsp;
&nbsp;
&nbsp;

Thanks in advance. :thumbsup:

**Comment by contribucious** [comment]
# :gear: Attempted technical analysis
&nbsp;

**Preamble:** all GitHub links in this post include [recent changes](https://github.com/AdguardTeam/BrowserAssistant/commit/f415dca0cd934cc082ff2762c8188308be83d1d8) made by @tvinzz related to issue #41 but in my opinion, this code modification doesn't change anything to this issue (nor does it change my "cold" analysis). :heavy_check_mark:
&nbsp;

<details>
<summary>Read me …</summary>
&nbsp;

### These tab actions for example correctly set the shield color to green:
- reloading the current tab ([`TAB_UPDATED`](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L29)) or
- opening a new tab ([`TAB_ACTIVATED`](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L28)).

- :arrow_right: See this [screenshot](https://user-images.githubusercontent.com/4764956/140243880-1353610b-0077-4823-88e0-24c6ba54e77e.png) for the latter. _(The result will remain correct after closing the latter via `Ctrl+W` to return to our initial tab, as it generates similarly another `TAB_ACTIVATED` event.)_

The problem here concerns the [`STATE_UPDATED`](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L30) event I would say.
&nbsp;

### Right away, a "cold" analysis allows to know that this event is correctly received:

Indeed, on a `non http(s) page` like the built-in new tab page (see `Interesting fact` above), [`setIconEnabled`](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L53) is correctly called. _(And, quite logically, the time between the click on "Enable protection" from the AdGuard icon and the color change of the shield in AG Browser Assistant is almost instantaneous because there is no response to wait in this case.)_

:arrow_right_hook: [The condition](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L52) being fulfilled because of [THIS](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L50) going back to [THIS](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L45) going back to [THIS](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/state.js#L256) (_"Returns […] null if url is not http"_).

##### :warning: On a `http(s) page` however, the condition is not met.

:arrow_right_hook: Logically, by going back the thing, because of the [response](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/state.js#L272) received when the [request](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/api/nativeHostApi.js#L261) is made, **at this precise moment at least**.
&nbsp;

### :bulb: Wouldn't the request simply be made too quickly once the `STATE_UPDATED` event is received? #idea
#### If not, it will be a matter of analyzing why this non-response _or_ negative response. Since this leads to the non-validation of [the condition](https://github.com/AdguardTeam/BrowserAssistant/blob/585bdcb3452281e84867622a76fdbe81a9442a48/src/background/icon.js#L52) required to obtain a green shield.
</details>
&nbsp;

**Comment by vozersky** [comment]
@contribucious Hello! Thanks for such a great feedback. A new [beta](https://chrome.google.com/webstore/detail/adguard-browser-assistant/hhaeiccdiaojoofohjiennalnphobkaf) should handle this issue, please give it a try, if you have a chance.

**Comment by contribucious** [comment]
@vozersky Hello Vladimir! :wave:
&nbsp;

I just tested this beta (version `1.1.31`) on Edge `95.0.1020.44` using `Windows 10 Pro Version 21H1 (OS Build 19043.1288)`.
This issue is not resolved.
&nbsp;

### Changes observed regarding this issue

- Regarding the AG B. A. behavior after clicking on `Enable protection` from the AdGuard icon in the notification area:
  &nbsp;
  :arrow_right: no change, still problematic (AG B. A. icon remains gray in all windows).
  **To be clear here:** I mean … _without_ performing an action that triggers an event, like a tab switch.
&nbsp;

### Other changes observed

1) Regarding the AG B. A. behavior after clicking on `Disable protection` from the AdGuard icon in the notification area:
  &nbsp;
  :arrow_right: differs in the beta in that the refresh of the AG Browser Assistant icon is now instantaneous (instead of being after a few seconds, synchronous with the AdGuard icon).
&nbsp;

2) **Another problem is now solved:** if we have two windows for example, each with two tabs, a tab switch in a window (which triggers the [`TAB_ACTIVATED`](https://github.com/AdguardTeam/BrowserAssistant/blob/afb17bafc9701ec713b745396b901e9aa141880f/src/background/icon.js#L27) event) will now correctly refresh the AG Browser Assistant icon in _all_ windows and not just in the active window as before.
  &nbsp;
  :arrow_right_hook: **i.e.** as described by @tvinzz in [its recent commit](https://github.com/AdguardTeam/BrowserAssistant/commit/15ab1bc4b31729005b4e171c4066c36d479a0c63): :thumbsup:
  `Icon state for active tabs in different windows` / `fixed icon state in different windows`.
&nbsp;

### I remain at your disposal. :v:

**Comment by contribucious** [comment]
:wave: I can confirm that the issue is resolved on my end as well. :thumbsup:

**Tested on:**
- AdGuard Browser Assistant 1.2.2 (Edge 98.0.1108.50)
- AdGuard Browser Assistant Beta 1.3.2 (Edge 98.0.1108.50)
- AdGuard Browser Assistant 1.3.2 (Firefox 97.0)

… with AdGuard 7.8 on Windows 10 Pro 21H2 (OS Build 19044.1526).

#### Thanks again to the team! :v: :wink:
