### ISSUE TITLE
AdGuard Browser Assistant Beta icon is permanently grey until clicked in Google Chrome Beta

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/BrowserAssistant#50]
The AdGuard Browser Assistant Beta icon is permanently grey until clicked in Google Chrome Beta giving a false indication to the user that AdGuard is disabled.
Once clicked, the icon appears green until deselected.

It seems that disabling AdGuard via the Browser Assistant, then enabling it again makes it work as it should.

Possibly AdGuard isn't aware of the current state on first install of the Browser Assistant, until the user changes the enable state.

<img width="32" alt="Screen Shot 2021-12-10 at 19 31 35" src="https://user-images.githubusercontent.com/95468948/145552044-e0f7c4e1-c1f6-49ea-904f-16da4a2be9bc.png">

**Comment by Birbber** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u We couldn't reproduce the issue on our end. Please tell us the configuration you use (your os, browser version, AdGuard Assistant version).

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> @gGkAC3qfszbdViFkw4Fk9ooS2u We couldn't reproduce the issue on our end. Please tell us the configuration you use (your os, browser version, AdGuard Assistant version).

macOS Monterey 12.1
Google Chrome Beta 97.0.4692.45
AdGuard Application 2.7.0.1073 nightly (CL-1.8.256, DNS-1.6.66)
AdGuard Browser Assistant Beta 1.2.2

**Comment by Birbber** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u Still couldn't reproduce with the same configuration. Have you tried with release version of Chrome?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
I was able to reproduce this on a MBP running High Sierra.
All I did was install the stable versions of all the above mentioned software.

There are no special configurations.

**Comment by Birbber** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u Sorry for the late reply!
Could you tell a bit more about installation order: first the application and then the extension, or vice versa?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
I am unable to reproduce again on either machine after fixing the issue locally.

Issue closed unless it can be repro'd.
