### ISSUE TITLE
Broken dark theme in Chrome

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/BrowserAssistant#51]
I'm using Windows AdGuard in dark theme but AdGuard Browser Assistant is not dark theme, I reinstalled Assistant but it doesn't work
![image](https://user-images.githubusercontent.com/35523759/147348036-546049a0-1aca-4a02-9743-3c745554dc7e.png)
![image](https://user-images.githubusercontent.com/35523759/147348069-e8492535-5306-4a59-9548-8202083cdfa1.png)

**Comment by Aydinv13** [comment]
You should set the needed theme in the system settings in order for the Browser assistant theme to change
