### ISSUE TITLE
Assistant not detecting AdGuard installation

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/BrowserAssistant#58]
@FauconSpartiate commented on [Sat Dec 25 2021](https://github.com/AdguardTeam/AdguardAssistant/issues/367)

AdGuard assistant doesn't detect any AdGuard installation, even though it is on default settings. I tried messing around with some settings, but nothing changed.

![image](https://user-images.githubusercontent.com/49079695/147391007-c00c8903-809f-4793-8b2c-80a033389d63.png)

- Latest Windows 10 build
- AdGuard Windows stable / beta / nightly

---

@Aydinv13 commented on [Mon Dec 27 2021](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1001410188)

What browser do you use? Which version of AdGuard&Browser assistant is it? 

---

@zzebrum commented on [Fri Jan 28 2022](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1024297251)

@FauconSpartiate any news? 

---

@FauconSpartiate commented on [Fri Jan 28 2022](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1024323512)

@Aydinv13 
Latest stable Chrome build, and latest release Adguard version

---

@FauconSpartiate commented on [Fri Jan 28 2022](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1024323957)

@zzebrum 
Nope, it has been ongoing since I first installed it, and is still broken...

---

@Aydinv13 commented on [Fri Jan 28 2022](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1024449628)

@FauconSpartiate have you tried to reinstall Browser Assistant?
- Remove Assistant from Chrome
- Go to AdGuard's settings-> Browser Assistant
- Click on `Get the extension` (previously, you need to set Chrome as your default browser)

---

@FauconSpartiate commented on [Fri Jan 28 2022](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1024541726)

Yep, reinstalled the extension, Adguard, and even chrome, but still the same...

---

@ameshkov commented on [Sun Jan 30 2022](https://github.com/AdguardTeam/AdguardAssistant/issues/367#issuecomment-1025164141)

Is it normal Chrome installation or something like a portable version?

Is AdGuard able to detect Chrome (this can be seen on the browser assistant settings screen).

**Comment by FauconSpartiate** [comment]
![image](https://user-images.githubusercontent.com/49079695/153671190-74553135-8e75-43ba-9667-f3857a926192.png)

AdGuard correctly detects Chrome, and it's a completely normal Chrome installation from the official installer

**Comment by vozersky** [comment]
@FauconSpartiate Hi, please try the latest Assistant v1.3.2, it's available now

**Comment by Chinaski1** [comment]
@FauconSpartiate 

Still not reproduced on our side.
I want to ask you to collect some information which will help to understand the causes of the issue

1. Restart the AdGuard application
2. Install AdGuard extension and restart the browser
3. Open Extensions section in the Chrome -> Enable `developer mode` -> Click on [`background page`](https://uploads.adguard.com/Chinask1wwn2p.png)
4. Check `console` log and send it to us if it contains any errors
5. Also, be advisable if you make a recording of the screen while the problem is reproducing and send it to devteam@adguard.com with a link to this task

**Comment by FauconSpartiate** [comment]
![image](https://user-images.githubusercontent.com/49079695/154533404-34c637c0-be10-48ab-a7e3-83ecb2ebd7b5.png)

@Chinaski1 
Jup I got some stuff in there... 
Can you make any sense out of it?

**Comment by FauconSpartiate** [comment]
Support team helped me solve the problem, my COMSPEC environment variable wasn't set. Adding it fixed the issue.
