### ISSUE TITLE
There is unnecessary empty space in UI

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/BrowserAssistant#61]
On the AdGuard Assistant, there's too little space below but too much space above.

![bug1](https://user-images.githubusercontent.com/35523759/155446899-3fb9ec60-0386-40a9-b476-361fba4269d2.jpg)

![bug2](https://user-images.githubusercontent.com/35523759/155446903-d846c7ab-06b4-486c-a6eb-00c79401039a.jpg)

**Comment by Birbber** [comment]
@gork7777 Hi. Looks like it depends on the browser you use. I do have the same visual in Chrome, but it looks fine in Firefox. Will see if we can do anything about it. Thanks!

**Comment by gork7777** [comment]
@Birbber Same for Edge browser too. Also there's problem for the colors too. In Edge, don't filter for 30 seconds and block ads on this site button colors are different. In chrome, they changed the buttons colors but they didn't change other browsers, you can check: https://github.com/AdguardTeam/BrowserAssistant/issues/52

Edge:
![edge](https://user-images.githubusercontent.com/35523759/155602732-6de92ee2-a510-4cc3-aa47-91fe68301068.png)

**Comment by Birbber** [comment]
@gork7777 Weird. I've checked Edge and colors look the way they suppose to: https://uploads.adguard.com/annrgy_edge.png 
Do you use the latest version of Edge?

**Comment by gork7777** [comment]
@Birbber Yes I'm using 98.0.1108.62 version. I cleared browser cache but didn't work.

**Comment by gork7777** [comment]
Assistant version shows 1.2.2 for Edge, but 1.3.6 for Chrome.

**Comment by Birbber** [comment]
@gork7777 Yeah, I had this version installed from Chrome store, sorry. This version is still being reviewed in Microsoft Store. I've added this info to release notes.

**Comment by gork7777** [comment]
Alright thanks!
