### ISSUE TITLE
Question about new features

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/BrowserAssistant#62]
Will there be new features for the assistant? Some suggested features have been almost 1-2 years and I can't see any updates.

**Comment by Birbber** [comment]
@gork7777 We haven't planned on implementing anything any time soon. What features are you referring to?

**Comment by gork7777** [comment]
@Birbber These: https://github.com/AdguardTeam/BrowserAssistant/issues/36, https://github.com/AdguardTeam/BrowserAssistant/issues/11, https://github.com/AdguardTeam/BrowserAssistant/issues/12, https://github.com/AdguardTeam/BrowserAssistant/issues/17

**Comment by ameshkov** [comment]
They may happen in the future, but not until we finish with MV3 versions of AdGuard extensions. It's a higher priority since Google plans to enforce it next year.

**Comment by gork7777** [comment]
Nice! Thank you.
