### ISSUE TITLE
Domain font inconsistency in AdGuard icon

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/BrowserAssistant#64]
The letter 'i' appears as the letter 'l'. The letter 't' appears to have been slightly erased in the AdGuard icon. But fonts look neater in AdGuard panel(assistant), maybe you can change font for AdGuard icon.

https://user-images.githubusercontent.com/35523759/156888466-a9e2a556-4921-4fa9-99e8-38920141f914.mp4

**Comment by Birbber** [comment]
@gork7777 So you mean the issue is observed in the legacy assistant? We no longer add any changes in it.

**Comment by gork7777** [comment]
Not sure it's a legacy assistant. Example: dizipal183.com appears as dlzlpal.com183.com in AdGuard icon (circle).

**Comment by zubrRB** [comment]
Browser Assistant at the top (dizipal183.com), Legacy Assistant at the bottom (d**l**z**l**pal183.com).
<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/156900546-00c4168a-ae4a-467f-9ab2-2687045b6690.png)
</details><br/>

**Comment by Birbber** [comment]
@gork7777 Legacy assistant is the one displayed at the bottom (the circle one), right. So as I can see the issue is observed only with the old assistant.
