### ISSUE TITLE
Why NOT supported on Android and AdguardHome?

### ISSUE THREAD

**Issue by Oxtie** [AdguardTeam/BrowserAssistant#65]
So I've 2 browsers in Android (one that supports chrome extensions and one that does NOT). At first, I tried to install web store version but once it failed, i got it from here (github and it got installed all right) BUT,.. since you people designed it for Windows, I now ask you people to make this Assistant support Adguard for Android AND Adguard Home (which is also in my router).

**Comment by Birbber** [comment]
@Oxtie Looks like it's impossible to implement what you're asking for, since we'll unlikely be able to integrate it.
