### ISSUE TITLE
Browser Assistant does not see the new site certificate

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/BrowserAssistant#68]
Срок действия сертификата сайта истёк, после чего он был продлён.  Но браузерный помощник спустя пять часов после этого смог увидеть новый сертификат только после перезапуска защиты (выключение/включение) в AdGuard для Windows. Неоднократный перезапуск браузера Chrome 100 и полная очистка в нём кеша не смогли исправить ситуацию.

![cert](https://user-images.githubusercontent.com/50718960/161919205-bdb23779-96e1-4240-b266-38f712689e33.png) ![cert2](https://user-images.githubusercontent.com/50718960/161919210-754a7504-306d-4f70-ae3e-356f8c52beae.png)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1619](https://github.com/AdguardTeam/CoreLibs/issues/1619) via [**ZenHub**](https://www.zenhub.com/)
