### ISSUE TITLE
favicon missing from AdGuard Browser Assistant homepage

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/BrowserAssistant#73]
https://adguard.com/en/adguard-assistant/overview.html

<img width="1593" alt="Screen Shot 2022-07-05 at 20 31 35" src="https://user-images.githubusercontent.com/95468948/177310321-08a91733-8b19-420e-8c59-9f1da9b22068.png">

**Comment by maximtop** [comment]
Thank you for reaching us. I wasn't able to reproduce issue with favicon in chrome and in firefox. 
Which browser do you use? 
Do you have any errors in the console in the developer tools?
