### ISSUE TITLE
Change the default font

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/BrowserAssistant#8]
@TheHasagi commented on [Thu May 28 2020](https://github.com/AdguardTeam/AdguardAssistant/issues/327)

In RU localization, the font is incorrectly displayed in the assistant window

<details>

![изображение](https://user-images.githubusercontent.com/37797229/83163802-20354000-a114-11ea-9a18-43f6d0d47ead.png)

</details>

**Comment by ArtemBaskal** [comment]
Solved https://github.com/AdguardTeam/BrowserAssistant/commit/4f255f4a8dede750190b4c10102b81ffeac516ec

**Comment by zzebrum** [comment]
let's keep it open until the new version release

**Comment by Rakleed** [comment]
@zzebrum наверное теперь можно закрыть эту issue?

**Comment by TheHasagi** [comment]
Fixed.
