### ISSUE TITLE
AdGuard assistant support for Vivaldi

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/BrowserAssistant#84]
Users ask to add Vivaldi browser to the list of supported browsers by AdGuard Browser Assistant.

**Comment by ameshkov** [comment]
You should file this to AdGuard for Win or Mac repos (if both products miss Vivaldi support you should file it to both repos).

**Comment by alexx7311** [comment]
Filed to [AdguardForWindows](https://github.com/AdguardTeam/AdguardForWindows) and [AdguardForMac] (https://github.com/AdguardTeam/AdguardForMac)
