### ISSUE TITLE
`$generichide` + `$generichide,badfilter` causes that protection cannot be enabled/disabled

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/BrowserAssistant#85]
It's impossible to enable/disable protection when `$generichide` + `$generichide,badfilter` rules are added.

Steps to reproduce
1. Add these rules:
```adblock
@@||example.org^$generichide
@@||example.org^$generichide,badfilter
```
2. Go to - https://example.org/
3. Click on assistant icon

Assistant shows:
>Filtering is disabled because it may affect the website's performance.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/198689610-c35ae54b-9ba4-40bc-8e3c-95ff318d57d5.png)

</details>

Similar issue occurs with `Legacy Assistant` - https://github.com/AdguardTeam/AdguardAssistant, so I'm not sure if it's a correct place to report it.

AdGuard for Windows 7.11 nightly 22 (build 4087, CL 1.10.106)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1681](https://github.com/AdguardTeam/CoreLibs/issues/1681) via [**Zenhub**](https://www.zenhub.com/)
