### ISSUE TITLE
Popup height is not readjusted after toggling website protection twice in Chrome/Edge

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/BrowserAssistant#86]
### _(:wave:)_ Steps to reproduce
1. Go to https://example.org.
2. Open the Browser Assistant popup.
3. Click on the toggle switch to disable the protection on the website (new entry `Remove all user rules for this page` appears at the bottom).
4. **Without closing the popup**, click again on the toggle switch to re-enable the protection now (entry `Remove all user rules for this page` disappears as expected _but_ the popup height is not readjusted).

<details>
<summary>:movie_camera: Video</summary>

https://user-images.githubusercontent.com/4764956/201468175-790aca30-13e2-4ac2-a3d9-e1fabc47b8c9.mp4
</details>

### :writing_hand: To be noted

More like a clue than a real fix, but `#root, html, body { height: 99.99%; }` instead of `#root, html, body { height: 100%; }` fixes the problem, as seen in the video below.
<details>
<summary>:movie_camera: Video</summary>

https://user-images.githubusercontent.com/4764956/201470121-7ecf18aa-4bd0-4369-af7f-d4c0a9795b19.mp4
</details>
&nbsp;

___
#### Thanks! :v:

<details>
<summary>Reveal env. …</summary>

- **Browser Assistant** 1.3.28 Beta
  - :information_source: Reproducible on both `Chrome` 107.0.5304.107 (latest stable) and `Edge` 107.0.1418.42 (latest stable)
  - :information_source: _**Not**_ reproducible on `Firefox` 106.0.5 (latest stable)

- **AdGuard** 7.11 nightly 24

- **Windows** 10 Pro 21H2 (OS Build 19044.2251)
</details>

**Comment by maximtop** [comment]
@contribucious thank you, your clue looks to me like a legit way to fix this issue

**Comment by contribucious** [comment]
My pleasure! :v: :wink:

**Comment by maximtop** [comment]
I've checked, and it doesn't work if the height is changed dynamically.
