### ISSUE TITLE
If you exit AdGuard and open settings from Assistant while the service is running, AdGuard won't open

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/BrowserAssistant#90]
As you can see in the video, if you try to open the settings in Assistant, AdGuard will not open. But if you open the filtering log from Assistant, the filtering log will be open.

<details><summary>Video</summary>

https://user-images.githubusercontent.com/35523759/210123108-a545249a-5bca-4c02-b108-39730a6a58c8.mp4
</details>

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #4556](https://github.com/AdguardTeam/AdguardForWindows/issues/4556) via [**Zenhub**](https://www.zenhub.com/)
