### ISSUE TITLE
Assistant says it is not updated when opening the browser

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/BrowserAssistant#97]
1. Install AdGuard for Windows
2. Install Assistant (e.g. in Chrome)
3. Open AdGuard
4. Open the browser (Chrome)

As a result, "Assistant is not updated" is written in popup

<details>

https://user-images.githubusercontent.com/73467237/229753926-9911a897-a452-43ff-8790-6d2f81eff7ac.mp4
</details>

**Comment by gork7777** [comment]
This may already be fixed in [#4663](https://github.com/AdguardTeam/AdguardForWindows/issues/4663)

**Comment by zubrRB** [comment]
`7.13 beta 3` все равно пока повторяется при запуске и сам Chrome заметно дольше стал загружаться. 
<details><summary>Screenshot:</summary>

![sshot-1](https://user-images.githubusercontent.com/50718960/236125592-58215474-fee0-4288-a3db-84e1d77b5c37.png)
</details><br/>

**Comment by zubrRB** [comment]
`7.13 RC` все равно пока повторяется при запуске и сам Google Chrome заметно дольше стал загружаться. 
<details><summary>Screenshot:</summary>

![sshot-1](https://user-images.githubusercontent.com/50718960/236125592-58215474-fee0-4288-a3db-84e1d77b5c37.png)
</details><br/>
